### ISSUE TITLE
自定义模板语音告警不生效

### ISSUE THREAD

**Issue by yangchuansheng** [feiyu563/PrometheusAlert#106]
阿里云语音告警配置失败，配置格式为自定义模板的格式：

```yaml
"receivers":
- "name": "Call"
  webhook_configs:
  - url: "http://10.108.166.207:8080/prometheusalert?type=alydh&tpl=prometheus-dh&phone=13999999999"
```

日志：

```bash
2021/02/21 07:20:12.269 [E] [prometheusalert.go:109]  [1613892012081140072] [alyphonecall] SDK.ServerError
ErrorCode: MissingCalledNumber
Recommend: https://error-center.aliyun.com/status/search?Keyword=MissingCalledNumber&source=PopGw
RequestId: F4C3FB69-6EBE-44B3-8C68-39F11217E584
Message: CalledNumber is mandatory for this action.
2021/02/21 07:20:12.269 [I] [prometheusalert.go:109]  [1613892012081140072] [alyphonecall] HTTP/1.1 400 Bad Request
Date: Sun, 21 Feb 2021 07:20:12 GMT
Access-Control-Allow-Methods: POST, GET, OPTIONS
Access-Control-Allow-Headers: X-Requested-With, X-Sequence, _aop_secret, _aop_signature
Access-Control-Max-Age: 172800
X-Acs-Request-Id: F4C3FB69-6EBE-44B3-8C68-39F11217E584
Content-Type: application/json;charset=utf-8
Content-Length: 270
Connection: keep-alive
Access-Control-Allow-Origin: *

{"RequestId":"F4C3FB69-6EBE-44B3-8C68-39F11217E584","Message":"CalledNumber is mandatory for this action.","Recommend":"https://error-center.aliyun.com/status/search?Keyword=MissingCalledNumber&source=PopGw","HostId":"dyvmsapi.aliyuncs.com","Code":"MissingCalledNumber"}
```

感觉应该没有获取到 phone 的值，是不是代码里的逻辑出现了问题？
