### ISSUE TITLE
Nginx 配置负载问题

### ISSUE THREAD

**Issue by foreveryang321** [feiyu563/PrometheusAlert#110]
> docker（192.168.123.1）
```yaml
version: '3.8'

services:
  prometheusalert:
    image: feiyu563/prometheus-alert:v-4.3.3
    container_name: ts_prometheusalert
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8080:8080"
    volumes:
      - "./prometheusalert_home/conf:/app/conf"
    restart: always
```

> Nginx 负载配置（http://vvip:80）
```txt
location ~ /prometheus-alert/ {
    proxy_pass         http://prometheus-alert;
}

upstream prometheus-alert {
        server 192.168.123.1:8080;
}
```

通过负载链接访问 http://vvip:80/prometheus-alert/ 静态资源引用有问题
> 源码中静态资源引用
```html
<link href="/static/css/bootstrap.min.css" rel="stylesheet" />
<link href="/static/css/docs.css" rel="stylesheet" />
```

如果需要给`prometheus-alert`配置访问`context-path`，静态资源引用不能使用绝对路径，而应该使用相对路径
```html
<link href="static/css/bootstrap.min.css" rel="stylesheet" />
<link href="static/css/docs.css" rel="stylesheet" />
```
否则`Nginx`只能如下配置,`prometheus-alert`才正常
```txt
location / {
    proxy_pass         http://prometheus-alert;
}
```

请问，如果要配置`context-path`，不需要使用方改源码的情况下，有其他解决方案吗
