### ISSUE TITLE
怎能配置多个dingding 告警

### ISSUE THREAD

**Issue by trestea** [feiyu563/PrometheusAlert#188]
prometheusalert 版本：v4.6.1
prometheusalert 配置：
  #---------------------↓webhook-----------------------
  #是否开启钉钉告警通道,可同时开始多个通道0为关闭,1为开启
  open-dingding=1
  #默认钉钉机器人地址
  ddurl=https://oapi.dingtalk.com/robot/send?access_token=xxxxx
  #是否开启 @所有人(0为关闭,1为开启)
  dd_isatall=1

怎么配置多个ddurl让alertmanager router选择哪个发送。

**Comment by Zhang21** [comment]
你在prometheus rules中写上不通的地址就可以了。

```yaml
annotations:
  wxurl: webhook1,webhook2...
```

**Comment by trestea** [comment]
@Zhang21 
如果按照您这种写法，所有消息都会发送到2个webhook
我的意思是 根据路由特征 分别调用 不同的 钉钉通道。

**Comment by trestea** [comment]
alertmanager配置:
    receivers:
    - name: dingding1
      webhook_configs:
      - url: http://prometheus-alert-center:8080/prometheusalert?type=dd&tpl=prometheus-dd&dd1url=https://oapi.dingtalk.com/robot/send?access_token=12bff15df40673b96230e5147afa9104706ea02cd622b507
        send_resolved: true

    - name: dingding2
      webhook_configs:
      - url: http://prometheus-alert-center:8080/prometheusalert?type=dd&tpl=prometheus-dd&dd2url=https://oapi.dingtalk.com/robot/send?access_token=b0d66a012b673b96230e5147afa9104706ea02cd622b507
        send_resolved: true

**Comment by feiyu563** [comment]
你是想要这样的吧

```
global:
  resolve_timeout: 5m
route:
  group_by: ['instance']
  group_wait: 10m
  group_interval: 10s
  repeat_interval: 10m
  receiver: 'web.hook.prometheusalert'
  routes:
  - receiver: 'prometheusalert-weixin'
    group_wait: 10s
    match:
      level: '1'
  - receiver: 'prometheusalert-dingding'
    group_wait: 10s
    match:
      level: '2'
  - receiver: 'prometheusalert-feishu'
    group_wait: 10s
    match:
      level: '3'
  - receiver: 'prometheusalert-ruliu'
    group_wait: 10s
    match:
      level: '3'
  - receiver: 'prometheusalert-all'
    group_wait: 10s
    match:
      level: '4'
receivers:
- name: 'web.hook.prometheusalert'
  webhook_configs:
  - url: 'http://[prometheusalert_url]:8080/prometheus/alert'
- name: 'prometheusalert-weixin'
  webhook_configs:
  - url: 'http://[prometheusalert_url]:8080/prometheus/router?wxurl=https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxx'
- name: 'prometheusalert-dingding'
  webhook_configs:
  - url: 'http://[prometheusalert_url]:8080/prometheus/router?ddurl=https://oapi.dingtalk.com/robot/send?access_token=xxxxx'
- name: 'prometheusalert-feishu'
  webhook_configs:
  - url: 'http://[prometheusalert_url]:8080/prometheus/router?fsurl=https://open.feishu.cn/open-apis/bot/hook/xxxxxxxxx'
- name: 'prometheusalert-ruliu'
  webhook_configs:
  - url: 'http://[prometheusalert_url]:8080/prometheus/router?groupid=123456'
- name: 'prometheusalert-all'
  webhook_configs:
  - url: 'http://[prometheusalert_url]:8080/prometheus/router?wxurl=https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxx&ddurl=https://oapi.dingtalk.com/robot/send?access_token=xxxxx&email=123@qq.com&phone=15395105573'
```
