### ISSUE TITLE
请问配置电话报警的那段是在哪里配置的？

### ISSUE THREAD

**Issue by alexju88** [feiyu563/PrometheusAlert#2]
你好，
麻烦问下，配置电话报警的那段配置，是在哪个组件下哪个配置文件里配置的？看着不太像Alertmanager

**Comment by feiyu563** [comment]
```
groups:
    name: node_alert
  rules:
    alert: 主机CPU告警
    expr: node_load1 > 3
    labels:
      severity: warning
    annotations:
      description: "{{ $labels.instance }} CPU load占用过高"  #告警信息
      summary: "{{ $labels.instance }} CPU load占用过高已经恢复"  #告警恢复信息
      level: 3   #告警级别,告警级别定义 0 信息,1 警告,2 一般严重,3 严重,4 灾难
      mobile: 15888888881,15888888882,15888888883  #告警发送目标手机号(需要设置电话和短信告警级别)
      ddurl: "https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" #支持添加多个钉钉告警,用,号分割即可,如果留空或者未填写,则默认发送到配置文件中填写的钉钉地址
```
上面的这个配置文件是prometheus的告警rules文件,里面主要配置下level和下面的电话告警的phonecalllevel相等即可

电话告警只需要在我的这个告警中心的配置文件（conf/app.conf）里面配置你们腾讯的接口参数和告警级别即可.

```
#电话接口key
phonecallappkey=c24bxxxxxxxxxxxxxxxxxx
#电话模版ID
phonecalltpl_id=29xxxxxx
#电话sdk app id
phonecallsdkappid=140xxxxxx
#电话告警级别(等于4就进行语音告警) 告警级别定义 0 信息,1 警告,2 一般严重,3 严重,4 灾难
phonecalllevel=4
#默认拨打号码
#defaultphone=
#未使用user.csv或者user.csv中的号码轮询结束备用号码
backupphone=151xxxxxxxx
```

注意上面的配置里面defaultphone配置和user.csv只能二选一,配置了defaultphone就会默认出现告警直接拨打defaultphone的号码
