### ISSUE TITLE
关于prometheus报警模板的疑问

### ISSUE THREAD

**Issue by bogeit** [feiyu563/PrometheusAlert#22]
我集群里面是采用prometheus-operator部署的一整套prometheus报警系统，之前采用的是邮件以及企业微信报警，报警信息都是很完整的，且都是官方配置规则，我这边未做任何改动；今天测试了PrometheusAlert，是可以发送报警信息到飞书webhook的，但显示的报警信息不全，不知道这个有没有对接prometheus-operator上面所有rule规则的模板呢？prometheus-operator官方完整rule：https://github.com/coreos/kube-prometheus/blob/release-0.1/manifests/prometheus-rules.yaml
我复制了其中一个报警rule如下：
```
        expr: |
          absent(up{job="kube-scheduler"} == 1)
        for: 15m
        labels:
          severity: critical
      - alert: KubeStateMetricsDown
        annotations:
          message: KubeStateMetrics has disappeared from Prometheus target discovery.
          runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubestatemetricsdown
```

上面这条rule产生报警的邮件内容如下：
```
1 alert for severity=critical
--
View in AlertManager[1] 
[1] Firing
Labelsalertname = KubeStateMetricsDownprometheus = monitoring/k8
sseverity = critical
Annotations
message = KubeStateMetrics has disappeared from Prometheus target discovery.
runbook_url = https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubestatemetricsdownSource
```

今天实测PrometheusAlert发送飞书的报警信息如下：
```
PrometheusAlert故障告警信息
## [PrometheusAlertPrometheus故障告警信息](http://prometheus-xxx:xxxx/graph?xxxxxxxxx)

#### [KubeStateMetricsDown](http://alertmanagxxx0:xxxx)

###### 告警级别：信息

###### 开始时间：2020-04-20T12:58:17.64901609Z

###### 结束时间：0001-01-01T00:00:00Z

###### 故障主机IP：

##### 

![PrometheusAlert](https://raw.githubusercontent.com/feiyu563/PrometheusAlert/master/doc/alert-center.png)
```
