### ISSUE TITLE
支持MySQL存储，只给insert语句导入初始数据，不给表结构？

### ISSUE THREAD

**Issue by zlfzy** [feiyu563/PrometheusAlert#271]
`利用Navicat或命令行将db目录中的 prometheusalert.sql 导入数据库prometheusalert`

我反正打开看了prometheusalert.sql里面没有创建表

**Comment by zlfzy** [comment]
好像找到问题原因了，env设置配置不生效，到账程序认为没有启用MySQL，表结构是自动创建的，我现在用configmap的方式挂载app.conf了

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-alert
  namespace: tools
spec:
  selector:
    matchLabels:
      app: prometheus-alert
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus-alert
    spec:
      containers:
      - image: feiyu563/prometheus-alert:latest
        name: prometheus-alert
        env:
        - name: PA_LOGIN_USER
          value: "admin"
        - name: PA_LOGIN_PASSWORD
          value: "yunwei"
        - name: PA_TITLE
          value: "PrometheusAlert"
        - name: PA_OPEN_FEISHU
          value: "1"
        - name: PA_OPEN_DINGDING
          value: "1"
        - name: PA_OPEN_WEIXIN
          value: "1"
        - name: PA_DB_DRIVER
          value: "mysql"
        - name: PA_DB_HOST
          value: "172.26.x.x"
        - name: PA_DB_PORT
          value: "3306"
        - name: PA_DB_USER
          value: "root"
        - name: PA_DB_PASSWORD
          value: "xxxx"
        - name: PA_DB_NAME
          value: "prometheus_alert"
        - name: TZ
          value: "Asia/Shanghai"
        ports:
        - containerPort: 8080
          name: http
```

以上是我一开始用env设置参数的deploy文件，但不生效，包括设置login账号密码都不生效，现已改用configmap
