### ISSUE TITLE
【功能】从 Prom Labels 中获取主机组作为告警组

### ISSUE THREAD

**Issue by Zhang21** [feiyu563/PrometheusAlert#361]
背景：之前的告警组功能也是需要在 prom rules annotations 中配置 alertgroup 告警组，这样每个规则都需要手动配置告警组。

想法：通过在 Prometheus 收集指标的时候，给每个 exporter 添加 `hostgroup` 标签来提前分组，这样告警的时候，就使用分组的组来作为发送告警的告警组的缺省值，而无需再在告警规则中配置告警组。

将机器逻辑上分组，既便于 grafana 分组，也便于告警分组。这样是不是更灵活？

**Comment by Zhang21** [comment]
举个例子：

比如收集数据库的机器，将机器分组为 dba；收集中间件的机器，将机器分组为 mw。

```yml
- labels:
    hostgroup: dba
    hostname: mysql-demo-01
  targerts:
    - 127.0.0.1:9100
    - 127.0.0.1:9256
    - ...

- labels:
    hostgroup: mw
    hostname: es-demo-01
  targerts:
    - 127.0.0.1:9100
    - 127.0.0.1:9256
    - ...
```

**Comment by Zhang21** [comment]
一个示例的告警：不填写告警通知对象，程序从 `labels.hostgroup` 获取告警组。

```yml
  - alert: CPU负载大于2Cores
    expr: node_load1 > (instance:node_cpus:count * 2) 
    for: 4m
    labels:
      severity: critical
      level: 3
    annotations:
      description: "主机 {{ $labels.hostname }} CPU负载 {{ $value }}"
```
