### ISSUE TITLE
kubernetes yaml中deployment文件错误，需要更新

### ISSUE THREAD

**Issue by 912988434** [feiyu563/PrometheusAlert#98]
volumeMount中使用的volume名称有个错误
```
        volumeMounts:
        - name: prometheus-alert-center-conf-map
          mountPath: /app/conf/app.conf
          subPath: app.conf
        - name: prometheus-alert-center-conf
          mountPath: /app/user.csv
          subPath: user.csv
```
正确应为
```
        volumeMounts:
        - name: prometheus-alert-center-conf-map
          mountPath: /app/conf/app.conf
          subPath: app.conf
        - name: prometheus-alert-center-conf-map
          mountPath: /app/user.csv   
          subPath: user.csv
```
